services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: research_ai
      POSTGRES_USER: luna
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DB_NAME: research_ai
      DB_USER: luna
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: "5432"
      HF_TOKEN: ${HF_TOKEN}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api/
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
