# Generated by Django 6.0.6 on 2026-07-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatmessage_actual_engagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='assigned_condition',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='post_survey_completed',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pre_survey_completed',
        ),
        migrations.AddField(
            model_name='participant',
            name='role_order',
            field=models.CharField(choices=[('IG_CE', 'Idea Generator → Critical Evaluator'), ('CE_IG', 'Critical Evaluator → Idea Generator')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExperimentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField()),
                ('survey_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='chatbot.participant')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='phase',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='chatbot.experimentphase'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='chatbot.experimentphase')),
            ],
        ),
    ]
